language: python
python:
- '2.7'
- '3.4'
install: pip install tox
script: make test
deploy:
  provider: pypi
  user: allanklp
  password:
  secure: "PIe9KTBqC9PYInSeP0cbxv7CN/OjJgAokZD+1UaIjDhX0k1/5QAVc2ylpyQsDik/dyfoxakHdRs6MHzM64HPSxl+0rj+3J6kRRvWk79AYtYsXs5ovwDPPIgJ3J525I2Fo3jIpFRCxfS+9J+OH5O6Dc4+TXfa2r4rsb7RynlYoZjVSQ3RJNUjnEdn+gK3F5c6VhFdEc0QSTILSNCM5Y7ZF5IkAVcSTRWk2+51GdbUSU3F61/h4fu1CTls7IFfho9AfuXgy0bZsHeXE8DH9+XcgpHapBNbG6AdhJ9Wl7qzBmsvnNa6oc91Z9NE5UZ4krRf/v6805tpFIqEkUNiErPnhnbLDk/CRBiB0F/cVuCVMSdIPnCY3vcD99BkVAFmaMq9JL3dXXw+vr5SHzQPZ8rTRvzNsEIWK2dsHkGbNJTZuHfX8Ij5XYpiYxDwGtdfrfWyyAn9GK8R9aLXu5uWEu5SKieUfRbEuixp9uYIZQywzq4rck2SK1M8eOTVYmfZ/iRNPdAdmlxUkPsVptRZaLsQbAGuHZmVpZZadFLT++S8Dkh3UwixR4YedfCac9j91XvwLkrawahUnao0RqV+nJtBAHDszOOoWJ8W41Dhp2VcAjq2EA/Tp4YyWvX+AwCdU1JOmN2SpUTt5G6U7FgBTaJvGlho8uVTmA4J+FzmwfvQEhY="
  on:
    branch: master
    tags: true
