language: python
python:
- '2.7'
- '3.4'
install: pip install tox
script: make test
deploy:
  provider: pypi
  user: allanklp
  password:
    secure: qzLyErzg75mrcH3xSTffM/GfwvYnaYyJ1o8SueZomwLv78pvgZVtKKQiwspbyAVCi7V5SWmsh8i5wix3Hsmjm/gAyyNOiTOrjaN1VHzDolSQ+PQRg8PXJsZapsip9bWbFFZiohdr0Itb0VkwTH424aV7fDv0vEWVhiiyLeP9OeUagnLaKyBefqH4K8cnFbiS6zhr+hkexV2gbzECVZNyz87wGBMnBWkm+D1IVBINI+92F9HBFbo3D1fojQDrO5iWIIPjxXdko/dWex1N3tTX4W33DfdxrfLP/fYHLbRK3fE/kxaLVidUhghQtpFV+eBtv0uB63QvipCS/TXyfZKN53b0ymRba9wA+gQe9htWXS21hRc/qIutWd0/NYCRS8JZZSD3Yzy3jRu5iIW7RDjZrDluMHNtpgE5RMRC15TSLRn/TgAgtw51ibec2U/ta8IVnVv5Ww0JXmCVsrayxhdJCGM8MqcNhfmcpcj+DnvGIfCow0KxHcrPcd5hLg4eiDUjKa5Ite2n8/kgTtPb491grVH6Yg3jt4/w2GuesCi40O8Zca04nbD+jb6LNQprpjYxss20A4kdxD1TWqKynMmnJcfs9/F+1w12uPWzS6Ex9l7G6PZ5PfskHtItIoFQ+ucGjfX60Rpg4+KeHlFlbR8jXLXXXwrucval8PD9S+4oVt8=
  on:
    branch: master
